apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-tomcat8
spec:
  replicas: 1
  selector:
    matchLabels:
      env:  prod
      version:  tomcat8
  template:
    metadata:
      labels:
        env:  prod
        version:  tomcat8
    spec:
      containers:
        - image: tomcat:8.5.40
        #- image: tomcat:8
          imagePullPolicy: Always
          name:  tomcat8
          ports:
            - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-tomcat7
spec:
  replicas: 1
  selector:
    matchLabels:
      env:  prod
      version:  tomcat7
  template:
    metadata:
      labels:
        env:  prod
        version:  tomcat7
    spec:
      containers:
        - image: tomcat:7
          imagePullPolicy: Always
          name:  tomcat7
          ports:
            - containerPort: 8080

